"""
update_bq_schema_descriptions.py
================================
Populates clear, comprehensive table descriptions AND column-level documentation strings
for ALL 26 tables and views in BigQuery dataset `bav-personal-cloud.develop`.

Adheres strictly to user global rules:
- Primary and Foreign Keys defined in documentation.
- 100% of columns documented with purpose, format, and meaning.

Usage:
    poetry run python Scripts/BigQuery/update_bq_schema_descriptions.py
"""

from __future__ import annotations

import os
import sys
from typing import Dict, List, Optional
from google.cloud import bigquery

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
if _THIS_DIR not in sys.path:
    sys.path.insert(0, _THIS_DIR)

from db_operator import get_bigquery_client  # noqa: E402

PROJECT_ID: str = "bav-personal-cloud"
DATASET_ID: str = "develop"

# Master Documentation Dictionary for all Tables and Views
TABLE_DOCS: Dict[str, Dict[str, str]] = {
    # -------------------------------------------------------------------------
    # 1. BTOPBatchChunks
    # -------------------------------------------------------------------------
    "BTOPBatchChunks": {
        "_description": "Tracks multi-period chunked backtest queue and execution state (e.g. 2022, 2023, 2024 date chunks) for serverless QuantConnect Cloud ingestion.",
        "batch_id": "Primary Key. Unique identifier for the multi-period batch run (e.g. BATCH_4EVC_V1_2022_2024).",
        "backtest_id": "Foreign Key referencing the QuantConnect Cloud backtest ID for this specific date chunk.",
        "algo_code": "Short code identifying the strategy algorithm (e.g. 4EVC, 0AT, 1SAOP).",
        "chunk_index": "Sequential index of the date chunk within the batch run (1..N).",
        "start_date": "Start date boundary for this backtest chunk (YYYY-MM-DD).",
        "end_date": "End date boundary for this backtest chunk (YYYY-MM-DD).",
        "status": "Execution and ingestion status of the chunk (PENDING, RUNNING, COMPLETED, FAILED).",
        "created_at": "UTC timestamp when the batch chunk record was queued.",
        "updated_at": "UTC timestamp when the chunk status was last updated.",
    },

    # -------------------------------------------------------------------------
    # 2. BTOPCharts
    # -------------------------------------------------------------------------
    "BTOPCharts": {
        "_description": "Stores custom performance charts, benchmark series, and equity curve plot series generated by QuantConnect backtests.",
        "chartId": "Primary Key. Unique identifier formatted as <backtestId>_<chart_name>.",
        "backtestId": "Foreign Key referencing BTOPResults(backtestId).",
        "name": "Name of the chart or series (e.g. Benchmark, Strategy Equity, Drawdown).",
        "series": "JSON-serialized string of timestamped value pairs plotting the chart curve.",
    },

    # -------------------------------------------------------------------------
    # 4. BTOPErrors
    # -------------------------------------------------------------------------
    "BTOPErrors": {
        "_description": "Logs error messages, stack traces, and exception details emitted during QuantConnect backtest execution.",
        "errorId": "Primary Key. Unique error log entry identifier.",
        "backtestId": "Foreign Key referencing BTOPResults(backtestId).",
        "timestamp": "UTC timestamp when the error event occurred.",
        "message": "Error summary message.",
        "stackTrace": "Full Python or C# exception traceback.",
    },

    # -------------------------------------------------------------------------
    # 5. BTOPOrders
    # -------------------------------------------------------------------------
    "BTOPOrders": {
        "_description": "Raw order events ingested directly from QuantConnect backtest orders JSON files.",
        "order_id": "Primary Key formatted as <backtestId>_<order_internal_id>.",
        "backtestId": "Foreign Key referencing BTOPResults(backtestId).",
        "order_internal_id": "Numeric internal order ID assigned by QuantConnect.",
        "brokerId": "Brokerage order identifier string.",
        "order_time": "UTC timestamp when the order was submitted/filled.",
        "symbol": "Ticker symbol or option contract symbol traded.",
        "price": "Execution fill price.",
        "quantity": "Number of shares or contracts executed (positive for buy, negative for sell).",
        "value": "Total monetary order value (price * quantity * multiplier).",
        "tag": "Order tag string containing custom strategy metadata or parameters.",
        "type": "QuantConnect order type (e.g. Market, Limit, StopMarket).",
        "status": "Order fill status (e.g. Filled, Canceled, Invalid).",
        "direction": "Order direction (Buy, Sell, Hold).",
        "securityType": "Security type (e.g. Equity, Option, Future).",
    },

    # -------------------------------------------------------------------------
    # 6. BTOPParameterSet
    # -------------------------------------------------------------------------
    "BTOPParameterSet": {
        "_description": "Stores strategy parameters, indicators, and configuration thresholds passed to each backtest run.",
        "paramSetId": "Primary Key formatted as <backtestId>_params.",
        "backtestId": "Foreign Key referencing BTOPResults(backtestId).",
        "parameters": "JSON-serialized string of key-value strategy parameters.",
    },

    # -------------------------------------------------------------------------
    # 7. BTOPResearchGuide
    # -------------------------------------------------------------------------
    "BTOPResearchGuide": {
        "_description": "Catalog mapping algorithms, strategy codes, parameters, and design notes for research tracking.",
        "guideId": "Primary Key. Unique research guide record identifier.",
        "algo_code": "Short strategy identifier (e.g. 4EVC, 0AT, 1SAOP).",
        "title": "Title of the research study or strategy variant.",
        "description": "Summary description of hypotheses, parameters, and goals.",
    },

    # -------------------------------------------------------------------------
    # 8. BTOPResults
    # -------------------------------------------------------------------------
    "BTOPResults": {
        "_description": "Core registry table storing top-level metadata for all QuantConnect Cloud and local backtests.",
        "backtestId": "Primary Key. Unique 32-character hexadecimal or string identifier of the backtest run.",
        "name": "Human-readable name assigned to the backtest (e.g. BT_4EVC_V1_20251127_210419).",
        "created": "UTC timestamp when the backtest was submitted.",
        "status": "Completion status of the backtest (e.g. Completed, Failed).",
        "progress": "Execution progress percentage (0.0 to 1.0).",
        "backtestStart": "Configured start date of the backtest period.",
        "backtestEnd": "Configured end date of the backtest period.",
    },

    # -------------------------------------------------------------------------
    # 9. BTOPRollingWindowClosedTrades
    # -------------------------------------------------------------------------
    "BTOPRollingWindowClosedTrades": {
        "_description": "Rolling window closed trade statistics broken down by sub-period evaluation windows.",
        "rollingId": "Primary Key. Unique rolling window trade record identifier.",
        "backtestId": "Foreign Key referencing BTOPResults(backtestId).",
        "windowName": "Name or date range label of the rolling window.",
        "tradeCount": "Number of trades executed in the window.",
        "winRate": "Win rate proportion in the window.",
        "totalPnL": "Total net PnL accumulated in the window.",
    },

    # -------------------------------------------------------------------------
    # 10. BTOPRollingWindowPortfolioStats
    # -------------------------------------------------------------------------
    "BTOPRollingWindowPortfolioStats": {
        "_description": "Rolling window portfolio performance metrics (Sharpe, Drawdown, Net Profit) per sub-period.",
        "rollingPortId": "Primary Key. Unique rolling portfolio stats identifier.",
        "backtestId": "Foreign Key referencing BTOPResults(backtestId).",
        "windowName": "Name or date range label of the rolling window.",
        "sharpeRatio": "Sharpe ratio measured over the rolling window.",
        "drawdown": "Maximum drawdown percentage measured over the rolling window.",
        "netProfit": "Net profit percentage achieved over the rolling window.",
    },

    # -------------------------------------------------------------------------
    # 11. BTOPRollingWindowTradeStats
    # -------------------------------------------------------------------------
    "BTOPRollingWindowTradeStats": {
        "_description": "Rolling window trade performance stats (Average Win, Average Loss, Profit Factor) per sub-period.",
        "rollingTradeId": "Primary Key. Unique rolling trade stats identifier.",
        "backtestId": "Foreign Key referencing BTOPResults(backtestId).",
        "windowName": "Name or date range label of the rolling window.",
        "profitFactor": "Ratio of gross profits to gross losses over the window.",
        "avgTradePnL": "Average PnL per trade over the window.",
    },

    # -------------------------------------------------------------------------
    # 12. BTOPRuntimeStatistics
    # -------------------------------------------------------------------------
    "BTOPRuntimeStatistics": {
        "_description": "Real-time runtime health metrics captured during backtest execution (e.g. Equity, Fees, Holdings, PSR).",
        "runtimeStatId": "Primary Key formatted as <backtestId>_runtime.",
        "backtestId": "Foreign Key referencing BTOPResults(backtestId).",
        "equity": "Latest total portfolio equity value ($).",
        "fees": "Cumulative brokerage fees paid ($).",
        "holdings": "Current portfolio holdings value ($).",
        "netProfit": "Current net profit percentage.",
        "probabilisticSharpeRatio": "Probabilistic Sharpe Ratio (PSR) estimation.",
        "return": "Cumulative portfolio return percentage.",
        "unrealized": "Total unrealized profit/loss ($).",
        "volume": "Total dollar volume traded ($).",
    },

    # -------------------------------------------------------------------------
    # 13. BTOPStatistics
    # -------------------------------------------------------------------------
    "BTOPStatistics": {
        "_description": "Summary statistics object emitted by QuantConnect backtest engine containing 28 key portfolio KPIs.",
        "statisticId": "Primary Key formatted as <backtestId>_stats.",
        "backtestId": "Foreign Key referencing BTOPResults(backtestId).",
        "totalOrders": "Total number of order executions.",
        "averageWin": "Average gain on winning trades (%).",
        "averageLoss": "Average loss on losing trades (%).",
        "compoundingAnnualReturn": "Compounding Annual Return (CAR) percentage.",
        "drawdown": "Maximum peak-to-trough drawdown percentage.",
        "expectancy": "Mathematical expectancy per dollar risked.",
        "startEquity": "Initial starting capital ($).",
        "endEquity": "Final portfolio ending equity ($).",
        "netProfit": "Total net profit percentage.",
        "sharpeRatio": "Sharpe Ratio measuring risk-adjusted return.",
        "sortinoRatio": "Sortino Ratio measuring downside risk-adjusted return.",
        "probabilisticSharpeRatio": "Probabilistic Sharpe Ratio (PSR) metric.",
        "lossRate": "Proportion of losing trades (0.0 to 1.0).",
        "winRate": "Proportion of winning trades (0.0 to 1.0).",
        "profitLossRatio": "Ratio of average win size to average loss size.",
        "alpha": "Capital Asset Pricing Model (CAPM) Alpha.",
        "beta": "CAPM Beta relative to market benchmark.",
        "annualStandardDeviation": "Annualized standard deviation of portfolio returns.",
        "annualVariance": "Annualized portfolio return variance.",
        "informationRatio": "Information Ratio against benchmark.",
        "trackingError": "Tracking error standard deviation against benchmark.",
        "treynorRatio": "Treynor Ratio measuring systemic risk-adjusted return.",
        "totalFees": "Total brokerage commissions paid ($).",
        "estimatedStrategyCapacity": "Estimated strategy capital capacity ($).",
        "lowestCapacityAsset": "Ticker symbol of the asset with lowest capacity.",
        "portfolioTurnover": "Annualized portfolio turnover rate.",
    },

    # -------------------------------------------------------------------------
    # 14. BTOPTotalPerformanceClosedTrades
    # -------------------------------------------------------------------------
    "BTOPTotalPerformanceClosedTrades": {
        "_description": "QuantConnect platform engine closed trade records generated in TotalPerformance structure.",
        "tradeId": "Primary Key formatted as <backtestId>_<symbol>_<trade_num>.",
        "backtestId": "Foreign Key referencing BTOPResults(backtestId).",
        "symbol": "Ticker symbol of the asset.",
        "entryTime": "UTC timestamp when position was opened.",
        "entryPrice": "Execution price when opened.",
        "direction": "Position direction (Long, Short).",
        "quantity": "Number of contracts/shares.",
        "exitTime": "UTC timestamp when position was closed.",
        "exitPrice": "Execution price when closed.",
        "profitLoss": "Dollar profit or loss realized ($).",
        "totalFees": "Total transaction fees ($).",
        "mae": "Maximum Adverse Excursion ($).",
        "mfe": "Maximum Favorable Excursion ($).",
        "duration": "Total holding duration in hours/days.",
        "endTradeDrawdown": "Drawdown experienced at trade exit.",
        "isWin": "Boolean flag indicating whether trade was profitable.",
    },

    # -------------------------------------------------------------------------
    # 15. BTOPTotalPerformancePortfolioStats
    # -------------------------------------------------------------------------
    "BTOPTotalPerformancePortfolioStats": {
        "_description": "Authoritative platform portfolio performance statistics for each QuantConnect backtest run.",
        "portfolioStatId": "Primary Key formatted as <backtestId>_portstats.",
        "backtestId": "Foreign Key referencing BTOPResults(backtestId).",
        "averageWinRate": "Average win rate metric.",
        "averageLossRate": "Average loss rate metric.",
        "profitLossRatio": "Profit to loss ratio.",
        "winRate": "Official platform win rate (0.0 to 1.0).",
        "lossRate": "Official platform loss rate (0.0 to 1.0).",
        "expectancy": "Official trade expectancy.",
        "startEquity": "Initial portfolio starting equity ($).",
        "endEquity": "Final portfolio ending equity ($).",
        "compoundingAnnualReturn": "Official Compounding Annual Return (CAR).",
        "drawdown": "Official maximum peak-to-trough drawdown.",
        "totalNetProfit": "Official net profit percentage.",
        "sharpeRatio": "Official Sharpe Ratio.",
        "probabilisticSharpeRatio": "Probabilistic Sharpe Ratio.",
        "sortinoRatio": "Official Sortino Ratio.",
        "alpha": "CAPM Alpha.",
        "beta": "CAPM Beta.",
        "annualStandardDeviation": "Annualized standard deviation.",
        "annualVariance": "Annualized variance.",
        "informationRatio": "Information Ratio.",
        "trackingError": "Tracking error against benchmark.",
        "treynorRatio": "Treynor Ratio.",
        "portfolioTurnover": "Annualized turnover rate.",
        "valueAtRisk99": "99% Value at Risk (VaR).",
        "valueAtRisk95": "95% Value at Risk (VaR).",
    },

    # -------------------------------------------------------------------------
    # 16. BTOPTotalPerformanceTradeStats
    # -------------------------------------------------------------------------
    "BTOPTotalPerformanceTradeStats": {
        "_description": "Authoritative platform trade statistics (trade count, duration, profit factor) per backtest run.",
        "tradeStatId": "Primary Key formatted as <backtestId>_tradestats.",
        "backtestId": "Foreign Key referencing BTOPResults(backtestId).",
        "startDateTime": "First trade entry timestamp.",
        "endDateTime": "Last trade exit timestamp.",
        "totalNumberOfTrades": "Total number of completed trades.",
        "numberOfWinningTrades": "Number of winning trades.",
        "numberOfLosingTrades": "Number of losing trades.",
        "totalProfitLoss": "Total realized PnL ($).",
        "totalProfit": "Total gross profit ($).",
        "totalLoss": "Total gross loss ($).",
        "largestProfit": "Largest single trade profit ($).",
        "largestLoss": "Largest single trade loss ($).",
        "averageProfitLoss": "Average PnL per trade ($).",
        "averageProfit": "Average profit on winning trades ($).",
        "averageLoss": "Average loss on losing trades ($).",
        "averageTradeDuration": "Average trade duration string.",
        "averageWinningTradeDuration": "Average winning trade duration.",
        "averageLosingTradeDuration": "Average losing trade duration.",
        "medianTradeDuration": "Median trade duration string.",
        "medianWinningTradeDuration": "Median winning trade duration.",
        "medianLosingTradeDuration": "Median losing trade duration.",
        "maxConsecutiveWinningTrades": "Maximum consecutive winning trades.",
        "maxConsecutiveLosingTrades": "Maximum consecutive losing trades.",
        "profitLossRatio": "Profit/Loss ratio.",
        "winLossRatio": "Win/Loss ratio.",
        "winRate": "Win rate.",
        "lossRate": "Loss rate.",
        "averageMAE": "Average Maximum Adverse Excursion ($).",
        "averageMFE": "Average Maximum Favorable Excursion ($).",
        "largestMAE": "Largest Maximum Adverse Excursion ($).",
        "largestMFE": "Largest Maximum Favorable Excursion ($).",
        "maximumClosedTradeDrawdown": "Maximum closed trade drawdown.",
        "maximumIntraTradeDrawdown": "Maximum intra-trade drawdown.",
        "profitLossStandardDeviation": "Standard deviation of trade PnL.",
        "profitLossDownsideDeviation": "Downside deviation of trade PnL.",
        "profitFactor": "Profit factor (gross profit / gross loss).",
        "sharpeRatio": "Trade Sharpe ratio.",
        "sortinoRatio": "Trade Sortino ratio.",
        "profitToMaxDrawdownRatio": "Profit to max drawdown ratio.",
        "maximumEndTradeDrawdown": "Maximum end trade drawdown.",
        "averageEndTradeDrawdown": "Average end trade drawdown.",
        "maximumDrawdownDuration": "Maximum drawdown duration.",
        "totalFees": "Total fees paid ($).",
    },

    # -------------------------------------------------------------------------
    # 17. BTOPTrades
    # -------------------------------------------------------------------------
    "BTOPTrades": {
        "_description": "Normalized order execution trade logs (OPEN/CLOSE events) parsed from order JSONs.",
        "pk": "Unique Event Primary Key formatted as <backtestId>_<underlying>_<seq_num>_<action>.",
        "trade_id": "Composite Lifecycle Key formatted as <backtestId>_<underlying>_<seq_num> shared between OPEN and CLOSE events.",
        "backtestId": "Foreign Key referencing BTOPResults(backtestId).",
        "algo_code": "Short algorithm identifier (e.g. 4EVC, 0AT, 1SAOP).",
        "timestamp": "UTC timestamp of the trade event.",
        "underlying": "Ticker symbol of the underlying asset.",
        "action": "Trade action type: OPEN or CLOSE.",
        "qty": "Number of contracts or shares traded.",
        "strike": "Strike price of the option leg.",
        "near_expiry": "Expiration date of near option leg.",
        "far_expiry": "Expiration date of far option leg.",
        "vol_ratio": "Front-to-back IV ratio at entry.",
        "slope": "IV term structure slope at entry.",
        "ivrv_ratio": "IV to Realized Volatility ratio at entry.",
        "entry_price": "Execution price when opened.",
        "exit_price": "Execution price when closed (0.0 if OPEN).",
        "pnl": "Realized return percentage of trade (0.0 if OPEN).",
        "exit_reason": "Normalized exit reason category (Stop Loss, Take Profit, Time Exit, DTE Safety, Margin Call, Other).",
        "parameters": "JSON-serialized string of custom entry parameters.",
        "batch_id": "Foreign Key referencing BTOPBatchChunks(batch_id) for multi-chunk runs.",
        "chunk_index": "Sequential index of the date chunk within a batch run.",
    },

    # -------------------------------------------------------------------------
    # 18. orders_parsed_wide
    # -------------------------------------------------------------------------
    "orders_parsed_wide": {
        "_description": "Flat wide view of parsed order events with signal parameters extracted from order tags.",
        "order_id": "Primary Key formatted as <backtestId>_<order_internal_id>.",
        "backtestId": "Foreign Key referencing BTOPResults(backtestId).",
        "order_internal_id": "Numeric internal order ID.",
        "brokerId": "Broker order identifier.",
        "order_time": "UTC order fill timestamp.",
        "tag": "Raw tag string containing pipe-delimited indicators.",
        "u": "Underlying ticker symbol extracted from tag.",
        "leg": "Option leg type (NEAR/FAR).",
        "k": "Strike price extracted from tag.",
        "slope": "IV slope value extracted from tag.",
        "ivrv": "IV/RV ratio extracted from tag.",
        "vol_ratio": "Volume ratio extracted from tag.",
        "near_exp": "Near leg expiry date extracted from tag.",
        "far_exp": "Far leg expiry date extracted from tag.",
        "signal_ts": "Signal timestamp extracted from tag.",
        "price": "Order fill price.",
        "quantity": "Executed order quantity.",
        "value": "Monetary value of order.",
        "type": "Order type string.",
        "status": "Order status string.",
        "securityType": "Security type string.",
        "direction": "Order direction (Buy/Sell).",
    },

    # -------------------------------------------------------------------------
    # 19. v_4EVC_backtest_execution_comparison
    # -------------------------------------------------------------------------
    "v_4EVC_backtest_execution_comparison": {
        "_description": "Summary execution KPIs comparing 1:N backtests for 4EVC strategy in Looker scorecards and comparison matrices.",
        "backtestId": "Foreign Key identifying the backtest run.",
        "backtest_name": "Human-readable name of the backtest.",
        "algo_code": "Strategy short code (4EVC).",
        "backtestStart": "Backtest start timestamp.",
        "backtestEnd": "Backtest end timestamp.",
        "total_completed_trades": "Total completed trades reported by platform.",
        "platform_win_rate": "Official platform win rate (0.0 to 1.0).",
        "platform_loss_rate": "Official platform loss rate (0.0 to 1.0).",
        "platform_net_profit": "Official net profit percentage.",
        "compounding_annual_return": "Official Compounding Annual Return (CAR).",
        "platform_max_drawdown": "Official maximum peak-to-trough drawdown.",
        "platform_sharpe_ratio": "Official Sharpe Ratio.",
        "platform_sortino_ratio": "Official Sortino Ratio.",
        "total_execution_records": "Total order execution records in BTOPTrades.",
        "avg_holding_hours": "Average trade holding duration in hours.",
        "avg_vol_ratio_at_entry": "Average volume ratio at trade entry.",
        "avg_slope_at_entry": "Average IV slope at trade entry.",
        "avg_ivrv_ratio_at_entry": "Average IV/RV ratio at trade entry.",
    },

    # -------------------------------------------------------------------------
    # 20. v_4EVC_batch_concatenated_trades
    # -------------------------------------------------------------------------
    "v_4EVC_batch_concatenated_trades": {
        "_description": "Concatenates multi-period chunked backtests (2022, 2023, 2024) by batch_id into a single continuous time series, computing multi-year equity curves, cumulative PnL, drawdowns, and trade stats.",
        "pk": "Primary Key for trade leg.",
        "batch_id": "Foreign Key identifying the batch run.",
        "chunk_index": "Index of date chunk.",
        "backtestId": "QuantConnect backtest ID.",
        "algo_code": "Algorithm code.",
        "batch_trade_seq": "Continuous trade sequence number across all batch chunks (1..N).",
        "underlying": "Underlying ticker symbol.",
        "open_time": "UTC trade entry timestamp.",
        "close_time": "UTC trade exit timestamp.",
        "holding_duration_hours": "Holding duration in hours.",
        "qty": "Trade quantity.",
        "vol_ratio": "Volume ratio at entry.",
        "slope": "IV slope at entry.",
        "ivrv_ratio": "IV/RV ratio at entry.",
        "entry_price": "Entry execution price.",
        "exit_price": "Exit execution price.",
        "pnl": "Realized PnL percentage.",
        "exit_reason": "Normalized exit category.",
        "outcome": "Trade outcome (Winner, Loser, Open).",
        "batch_running_pnl": "Cumulative running PnL across all batch chunks.",
        "batch_running_max_pnl": "Peak running cumulative PnL.",
        "batch_drawdown": "Current drawdown from peak running PnL.",
    },

    # -------------------------------------------------------------------------
    # 21. v_4EVC_decile_signals
    # -------------------------------------------------------------------------
    "v_4EVC_decile_signals": {
        "_description": "Performs global NTILE(10) decile binning for 4EVC entry signals (vol_ratio, slope, ivrv_ratio) linked to Mean Realized Return PnL, providing exactly 10 decile buckets per metric for Looker research graphs.",
        "algo_code": "Algorithm short code (4EVC).",
        "metric_name": "Name of entry signal metric (vol_ratio, slope, ivrv_ratio).",
        "decile_bucket": "Decile bucket number (1..10).",
        "trade_count": "Number of trades in decile bucket.",
        "avg_metric_value": "Mean value of entry metric in decile bucket.",
        "min_metric_value": "Minimum metric value in decile bucket.",
        "max_metric_value": "Maximum metric value in decile bucket.",
        "decile_range_label": "Formatted range string (e.g. (0.001, 0.005]).",
        "mean_pnl": "Mean realized return PnL in decile bucket.",
        "zero_pnl_benchmark": "Zero reference line benchmark (0.0).",
        "total_pnl": "Sum of realized PnL in decile bucket.",
        "win_rate": "Proportion of winning trades in decile bucket.",
    },

    # -------------------------------------------------------------------------
    # 22. v_4EVC_trade_duration_distribution
    # -------------------------------------------------------------------------
    "v_4EVC_trade_duration_distribution": {
        "_description": "High-resolution continuous numeric binning for 4EVC trade holding duration distribution histograms in Looker Studio.",
        "pk": "Primary Key of trade leg.",
        "backtestId": "Backtest run ID.",
        "backtest_name": "Backtest name.",
        "algo_code": "Algorithm short code.",
        "trade_seq": "Trade sequence number.",
        "underlying": "Underlying ticker symbol.",
        "open_time": "Entry timestamp.",
        "close_time": "Exit timestamp.",
        "return_pct": "Realized return PnL percentage.",
        "outcome": "Trade outcome (Winner, Loser).",
        "holding_duration_hours": "Holding duration in hours.",
        "holding_duration_days": "Holding duration in days.",
        "duration_bin_hours": "Binned holding duration in 24-hour steps.",
        "duration_bin_days": "Binned holding duration in 1-day steps.",
        "duration_bin_label": "Human readable duration bin label.",
    },

    # -------------------------------------------------------------------------
    # 23. v_4EVC_trade_execution_sequence
    # -------------------------------------------------------------------------
    "v_4EVC_trade_execution_sequence": {
        "_description": "Sequences 4EVC trade execution order (1..N) per backtest, computing trade lifecycle KPIs, signal indicators, running cumulative PnL, and drawdowns from BTOPTrades with backtest_name.",
        "pk": "Primary Key of trade leg.",
        "backtestId": "Backtest run ID.",
        "backtest_name": "Backtest name.",
        "algo_code": "Algorithm short code.",
        "trade_seq": "Sequential trade number within the backtest (1..N).",
        "underlying": "Underlying ticker symbol.",
        "open_time": "UTC entry timestamp.",
        "close_time": "UTC exit timestamp.",
        "holding_duration_hours": "Holding duration in hours.",
        "qty": "Trade quantity.",
        "vol_ratio": "Volume ratio at entry.",
        "slope": "IV slope at entry.",
        "ivrv_ratio": "IV/RV ratio at entry.",
        "entry_price": "Entry execution price.",
        "exit_price": "Exit execution price.",
        "pnl": "Realized return PnL percentage.",
        "exit_reason": "Normalized exit category.",
        "outcome": "Trade outcome (Winner, Loser, Open).",
        "running_pnl": "Cumulative running PnL within backtest.",
        "running_max_pnl": "Peak cumulative running PnL.",
        "drawdown": "Drawdown from peak cumulative PnL.",
    },

    # -------------------------------------------------------------------------
    # 24. v_4EVC_trade_flow
    # -------------------------------------------------------------------------
    "v_4EVC_trade_flow": {
        "_description": "Produces a Sankey-ready edge list from BTOPTrades for 4EVC trade-flow visualization in Looker Studio.",
        "backtestId": "Backtest run ID.",
        "algo_code": "Algorithm short code.",
        "source_node": "Source node label in Sankey diagram.",
        "target_node": "Target node label in Sankey diagram.",
        "trade_count": "Number of trade flow transitions.",
        "avg_pnl": "Average PnL for trade flow transition.",
        "total_pnl": "Total PnL accumulated in trade flow transition.",
    },

    # -------------------------------------------------------------------------
    # 25. v_4EVC_trade_return_distribution
    # -------------------------------------------------------------------------
    "v_4EVC_trade_return_distribution": {
        "_description": "High-resolution numeric binning (0.01 resolution) for 4EVC trade return density histograms in Looker Studio.",
        "pk": "Primary Key of trade leg.",
        "backtestId": "Backtest run ID.",
        "backtest_name": "Backtest name.",
        "algo_code": "Algorithm short code.",
        "trade_seq": "Trade sequence number.",
        "underlying": "Underlying ticker symbol.",
        "open_time": "Entry timestamp.",
        "close_time": "Exit timestamp.",
        "return_pct": "Realized return percentage.",
        "outcome": "Trade outcome (Winner, Loser).",
        "return_bin": "Numeric return bin (0.01 step size).",
        "return_bin_label": "Percentage bin label.",
    },

    # -------------------------------------------------------------------------
    # 26. v_4EVC_trade_return_summary_stats
    # -------------------------------------------------------------------------
    "v_4EVC_trade_return_summary_stats": {
        "_description": "Pandas .describe() and VaR tail percentiles per backtest for 4EVC profit histograms in Looker Studio.",
        "backtestId": "Backtest run ID.",
        "backtest_name": "Backtest name.",
        "count": "Number of closed trades.",
        "mean": "Mean return percentage.",
        "std": "Standard deviation of returns.",
        "min": "Minimum return percentage.",
        "p25": "25th percentile (Q1) return.",
        "p50_median": "50th percentile (Median) return.",
        "p75": "75th percentile (Q3) return.",
        "max": "Maximum return percentage.",
        "var_5pct": "5% Value at Risk (95% confidence tail).",
        "var_1pct": "1% Value at Risk (99% confidence tail).",
        "var_01pct": "0.1% Value at Risk tail.",
        "var_001pct": "0.01% Value at Risk tail.",
    },

    # -------------------------------------------------------------------------
    # v_4EVC_sankey_trade_flow
    # -------------------------------------------------------------------------
    "v_4EVC_sankey_trade_flow": {
        "_description": "Standardized Sankey trade flow edge list linking orders sent, accepted, entered trades, performance status, and detailed exit reasons.",
        "backtestId": "Foreign Key referencing BTOPResults(backtestId).",
        "backtest_name": "Human-readable name assigned to the backtest (e.g. BT_4EVC_V1_20251127_210419).",
        "source": "Source node name in the Sankey flow diagram (e.g. Total Orders Sent, Winners, Losers).",
        "target": "Target node name in the Sankey flow diagram (e.g. Total Orders Accepted, Take Profit, Stop Loss).",
        "flow_value": "Count of order or trade events flowing between source and target nodes.",
    },

    # -------------------------------------------------------------------------
    # v_4EVC_flattened_trade_details
    # -------------------------------------------------------------------------
    "v_4EVC_flattened_trade_details": {
        "_description": "Flattened trade-by-trade view pairing entry/exit prices, holding duration, financial PnL ($ and %), option leg attributes, and strategy predictor variables.",
        "trade_id": "Unique trade identifier combining backtest ID, symbol, and trade sequence number.",
        "backtestId": "Foreign Key referencing BTOPResults(backtestId).",
        "backtest_name": "Human-readable name assigned to the backtest (e.g. BATCH_4EVC_V1_20260728_191135_Y2024).",
        "underlying": "Underlying ticker symbol (e.g. AAPL, NVDA, C).",
        "qty": "Quantity of calendar spread contracts traded.",
        "entry_time": "Timestamp when the trade entry combo order executed.",
        "exit_time": "Timestamp when the trade exit combo order executed (NULL if still open).",
        "holding_hours": "Holding duration in hours between entry and exit.",
        "net_entry_debit": "Net entry debit (cost paid) per contract for the calendar spread.",
        "net_exit_credit": "Net exit credit (revenue received) per contract upon closing.",
        "net_pnl_pct": "Percentage profit or loss realized on the trade.",
        "net_pnl_dollars": "Dollar profit or loss realized on the trade = (exit_credit - entry_debit) * qty * 100.",
        "strike": "Strike price of the call/put option legs.",
        "short_leg_expiry": "Expiration date of the short front-month option leg.",
        "long_leg_expiry": "Expiration date of the long back-month option leg.",
        "vol_ratio": "Predictor variable: Ratio of near-month Implied Volatility to far-month Implied Volatility (IV_near / IV_far).",
        "slope": "Predictor variable: Slope of the IV term structure curve.",
        "ivrv_ratio": "Predictor variable: Implied Volatility to Realized Volatility ratio.",
        "earnings_date": "Scheduled earnings report date for the underlying asset.",
        "exit_reason": "Categorized reason for exit (e.g. Take Profit, Stop Loss, DTE Safety, Margin Call, STILL OPEN).",
        "parameters": "Raw JSON string containing all additional strategy parameters and predictor values.",
    },
    # -------------------------------------------------------------------------
    # v_4EVC_enriched_trades
    # -------------------------------------------------------------------------
    "v_4EVC_enriched_trades": {
        "_description": "Authoritative enriched trade view joining QuantConnect Lean engine closed trade leg performance (entry/exit prices, PnL $, PnL %, fees, MAE, MFE, win/loss status) with strategy log metadata (vol_ratio, slope, ivrv_ratio, strike, expiries, earnings_date, and flattened parameters).",
        "engine_trade_id": "Primary Key identifying the closed trade leg from Lean engine.",
        "backtestId": "Foreign Key referencing BTOPResults(backtestId).",
        "backtest_name": "Human-readable backtest name.",
        "underlying": "Underlying ticker symbol (e.g. AAPL, NVDA, GEF).",
        "contract_symbol": "Exact option contract symbol (e.g. GEF 230915C00065000).",
        "leg_direction": "Order leg direction (BUY_TO_OPEN vs SELL_TO_OPEN).",
        "option_type": "Option contract type (CALL vs PUT vs EQUITY).",
        "qty": "Quantity of contracts traded.",
        "engine_entry_time": "Timestamp when position leg opened.",
        "engine_exit_time": "Timestamp when position leg closed.",
        "holding_hours": "Holding duration in hours.",
        "leg_entry_price": "Execution entry price per contract.",
        "leg_exit_price": "Execution exit price per contract.",
        "leg_pnl_dollars": "Dollar profit/loss realized on position leg.",
        "leg_pnl_pct": "Percentage return realized on position leg.",
        "leg_total_fees": "Total brokerage fees paid on position leg.",
        "leg_mae": "Maximum Adverse Excursion ($).",
        "leg_mfe": "Maximum Favorable Excursion ($).",
        "leg_end_drawdown": "End trade drawdown ($).",
        "win_loss_status": "Status categorization (WINNER vs LOSER).",
        "strike": "Option strike price.",
        "short_leg_expiry": "Short leg expiration date.",
        "long_leg_expiry": "Long leg expiration date.",
        "vol_ratio": "Predictor variable: Near-to-Far IV ratio.",
        "slope": "Predictor variable: IV term structure slope.",
        "ivrv_ratio": "Predictor variable: IV-to-RV ratio.",
        "earnings_date": "Scheduled earnings date.",
        "param_alpha_spread": "Flattened parameter: Alpha spread multiplier.",
        "param_target_dte": "Flattened parameter: Target DTE.",
        "param_holding_days": "Flattened parameter: Maximum holding days.",
        "param_min_vol_ratio": "Flattened parameter: Minimum Volatility Ratio threshold.",
        "raw_parameters_json": "Raw JSON string of strategy parameters.",
        "_ingested_at": "Timestamp when record was ingested into BigQuery.",
    },
}


def update_schema_descriptions(project_id: str = PROJECT_ID, dataset_id: str = DATASET_ID) -> None:
    print(f"\n========================================================")
    print(f" Updating Schema & Column Descriptions in `{project_id}.{dataset_id}`")
    print(f"========================================================\n")
    client = get_bigquery_client(project_id=project_id)
    dataset_ref = f"{project_id}.{dataset_id}"

    tables = list(client.list_tables(dataset_ref))

    for item in tables:
        t_id = item.table_id
        table = client.get_table(item.reference)
        doc_entry = TABLE_DOCS.get(t_id, {})

        # 1. Update Table Description
        table_desc = doc_entry.get("_description", f"Table/View `{t_id}` in dataset `{dataset_id}`.")
        table.description = table_desc

        # 2. Update Column Descriptions
        new_schema = []
        updated_cols_count = 0

        for field in table.schema:
            col_desc = doc_entry.get(field.name) or field.description or f"Field `{field.name}` of type {field.field_type}."
            new_field = bigquery.SchemaField(
                name=field.name,
                field_type=field.field_type,
                mode=field.mode,
                description=col_desc,
                fields=field.fields,
            )
            new_schema.append(new_field)
            updated_cols_count += 1

        table.schema = new_schema
        client.update_table(table, ["description", "schema"])
        print(f"[SUCCESS] Updated `{t_id}` ({table.table_type}): Table description + {updated_cols_count} column descriptions.")

    print(f"\n[SUCCESS] Completed schema description updates across all {len(tables)} tables and views!")


if __name__ == "__main__":
    update_schema_descriptions()
