ALGOS:
  - ALGO_CODE : 1
    ALGO_NAME : "StatisticalArbitrageOptionsPair"
    ALGO_MAYUS_LETTERS : "SAOP"
    ALGO_PUBLIC_NAME : "BarackObama"
    ALGO_VERSION : 1
    ALGO_PARAMETRY :
      - ALGO_PARAM_1 :
        ALGO_PARAM_1_DEFAULT : 15
        ALGO_PARAM_1_MIN : 10
        ALGO_PARAM_1_MAX: 20
        ALGO_PARAM_1_STEP: 5
      - ALGO_PARAM_2 : "full"
    ALGO_SHORT_NAME : "1SAOP"
    