defaults: &defaults
  LOGIN_USER: bryan.aleixo@gmail.com
  LOGIN_PWD: P@ssw0rd123
  LOGIN_API_KEY: 2d3f90f3268688177d95e83731b898974f4f9b7dda2e9f065aeb15ab9fee4f28
  USER_ORG_ID: "6bfd78b1c53c2e682ab8f3635d854f13"
  USER_CLOUD_ID: 19484516

environments:
  develop:
    <<: *defaults
    branch: dev-branch
    purpose: "Execute backtests and optimizations"

  paper:
    <<: *defaults
    branch: staging-branch
    purpose: "Place algorithms in paper execution, simulate live feed, test broker connections"

  market:
    <<: *defaults
    branch: main-branch
    purpose: "Real market data and live executions"
